server:
  port: 8013
  servlet:
    context-path: /ms/system/web
  tomcat:
    uri-encoding: UTF-8


spring:
  application:
    name: ms-system-web #\u6307\u5B9A\u670D\u52A1\u540D\u79F0
  #  mvc:
  #    view:
  #      prefix: /
  #      suffix: .jsp
  thymeleaf:
    cache: false
